version: 2
workflows:
   version: 2
   eb-sqs-jobs:
     jobs:
       - test-python-3
       - test-python-2
jobs:
  test-python-3:
    docker:
      - image: circleci/python:3.5-jessie
    steps:
      - add_ssh_keys
      - checkout
      - run:
          name: Install dependencies
          command: sudo pip install -r development.txt
      - run:
          name: Run tests
          command: python -m django test --settings=eb_sqs.test_settings
  test-python-2:
    docker:
      - image: circleci/python:2.7-jessie
    steps:
      - add_ssh_keys
      - checkout
      - restore_cache:
            key: deps9-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
      - run:
          name: Install dependencies
          command: |
            sudo pip install pipenv
            pipenv install -r development.txt
      - save_cache:
          key: deps9-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
          paths:
            - "/usr/local/bin"
            - "/usr/local/lib/python2.7/site-packages"
      - run:
          name: Run tests
          command: |
            pipenv run python -m django test --settings=eb_sqs.test_settings