version: 2
workflows:
   version: 2
   eb-sqs-jobs:
     jobs:
       - test-python-3-7
       - test-python-2-7
       - bump-version:
           filters:
             branches:
               only: /BNCASB-2204.*/
           requires:
             - test-python-3-7
             - test-python-2-7
jobs:
  test-python-3-7: &test-template
    docker:
      - image: circleci/python:3.7.6
    steps:
      - add_ssh_keys
      - checkout
      - run:
          name: Install dependencies
          command: |
            sudo pip install -r development.txt
      - run:
          name: Run tests
          command: |
            python -m django test --settings=eb_sqs.test_settings
  test-python-2-7:
    <<: *test-template
    docker:
      - image: circleci/python:2.7.16
  bump-version:
    docker:
      - image: circleci/python:3.7.6
      steps:
        - add_ssh_keys
        - checkout
        - run:
            name: Update version number
            command: |
              OLD_VER=$(cat VERSION) && NEW_VER=$(echo $OLD_VER + .01 | bc) && echo $NEW_VER > VERSION
              echo $OLD_VER
              echo $NEW_VER
              cat VERSION
        - run:
            name: Push to GitHub
            command: |
               echo "pushing to github..."
